### ISSUE TITLE
webserver is bad

### ISSUE THREAD

**Issue by zhaozhijun321** [Lucandia/dual_letter_illusion#10]
I tried to use your library, but it was wrong, the server reported an error
![1719803597221](https://github.com/Lucandia/dual_letter_illusion/assets/30647197/a395e2c5-fce8-4cd9-be5d-293644d69ccc)

**Comment by Lucandia** [comment]
Share the image, I'll have a look at it

**Comment by Lucandia** [comment]
They updated the numpy version to 2.0 and now half of the libraries don't work hahah
I had to explicitly set the numpy requirement to 1.26, now should work
