### ISSUE TITLE
Can't run project locally

### ISSUE THREAD

**Issue by stephansomers** [Lucandia/dual_letter_illusion#19]
Hey!
I'm trying to run this amazing project locally, but I'm facing issue that seems to be related to dependancies and python version.
Could you please share with me what versions did you use?

**Comment by Lucandia** [comment]
I think I'm using normal python 3.12 I think. Which errors do you get?

**Comment by stephansomers** [comment]
Firstly I got the cadquery module missing, but this was solved.

Then I got the following:
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

Have you had this before?

**Comment by Lucandia** [comment]
Hi,
 Yeah, I've been having a lot of problems with  Cadquery, lately. 
 Numpy has been updated to version 2.0, which is a problem for Cadquery, so make sure to install numpy 1.26, this should do the trick.
Alternatively, if possible, I suggest installing Cadquery and OCP with Ananconda, if you have a conda environment.
Let me know if this works!
Best,
 Luca

**Comment by stephansomers** [comment]
Hey, we were able to fix it with your help :)

I had to install streamlit and numpy==1.22, then fix the fonts folder path (from 'fonts' to '../fonts') and then I ran streamlit run app.py and it worked!

    font_dir = os.listdir('../fonts')
    with col1:
        font_name = st.selectbox('Select font', ['lato'] + sorted(font_dir))
    with col2:
        font_type_list = [f for f in os.listdir('../fonts' + os.sep + font_name) if '.ttf' in f and '-' in f]

Thank you so much for your help, this App is amazing!
