### ISSUE TITLE
Steamlit web app doesn't load

### ISSUE THREAD

**Issue by stavfx** [Lucandia/dual_letter_illusion#9]
Getting a blank page from https://dual-letter-illusion.streamlit.app/

**Comment by Lucandia** [comment]
It is working for me now. Maybe Streamlit servers were down, or you aren't using a supported browser (https://docs.streamlit.io/knowledge-base/using-streamlit/supported-browsers)

**Comment by stavfx** [comment]
Yup. working again. thanks
